//
//  Copyright © 2023 Embrace Mobile, Inc. All rights reserved.
//

// This file is automatically generated by the "${BASH_SOURCE[0]}" script
// Do not edit this file manually

class EmbraceMeta {
    static let sdkVersion = "6.0.0"
    static let gitSHA = ""
}
