//
//  Copyright © 2024 Embrace Mobile, Inc. All rights reserved.
//

// This file is automatically generated by the "bin/version_bump" script
// Do not edit this file manually

public class EmbraceMeta {
    public static let sdkVersion = "6.3.0-rc5"
}
