//
//  Copyright © 2024 Embrace Mobile, Inc. All rights reserved.
//

// This file is automatically generated by the 'version_bump' script
// Do not edit this file manually

public class EmbraceMeta {
    public static let sdkVersion = "6.7.1-rc1"
}
