version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github:
        patterns:
          - "actions/*"
      embrace-io:
        patterns:
          - "embrace-io/*"
  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "daily"
