version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      github:
        patterns:
          - "actions/*"
      embrace-io:
        patterns:
          - "embrace-io/*"

  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
