disabled_rules: # rule identifiers turned on by default to exclude from running
  - identifier_name
  - function_parameter_count
  - notification_center_detachment
  - compiler_protocol_init

opt_in_rules:
  - conditional_returns_on_newline

included: # case-sensitive paths to include during linting. `--path` is ignored if present
  - Sources

excluded: # case-sensitive paths to ignore during linting. Takes precedence over `included`
  - README.md
  - docs
  - Tests

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging, summary)

file_length:
  warning: 800
  error: 1000

line_length:
  ignores_comments: true
  ignores_interpolated_strings: true

type_body_length:
  warning: 600
  error: 800

type_name:
  max_length:
    warning: 60
  allowed_symbols: ["_"]

function_body_length:
  warning: 100
  error: 300

large_tuple:
  warning: 4
  error: 6

cyclomatic_complexity:
  ignores_case_statements: true
  warning: 20
  error: 30
