disabled_rules: # rule identifiers turned on by default to exclude from running
  - identifier_name
  - function_parameter_count
  - notification_center_detachment
  - compiler_protocol_init
  - for_where
  # Disable formatting-related rules to avoid conflicts
  - line_length
  - indentation_width
  - trailing_whitespace
  - vertical_whitespace
  - opening_brace
  - closing_brace
  - statement_position
  - function_body_length
  - type_body_length
  - file_length
  - closure_parameter_position # disable ??
  - todo # disable ??
  - type_name
  - deployment_target
  - cyclomatic_complexity
  - force_unwrapping
  
opt_in_rules:
  # - conditional_returns_on_newline
  - force_unwrapping
  - empty_count
  - fatal_error_message
  - force_cast
  - vertical_parameter_alignment_on_call

analyzer_rules:
  - unused_import
  - unused_declaration

included: # case-sensitive paths to include during linting. `--path` is ignored if present
  - Sources

excluded: # case-sensitive paths to ignore during linting. Takes precedence over `included`
  - README.md
  - docs
  - Tests

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging, summary)
