//
//  Copyright © 2025 Embrace Mobile, Inc. All rights reserved.
//

import Foundation

#if !EMBRACE_COCOAPOD_BUILDING_SDK
    import EmbraceSemantics
    import EmbraceCommonInternal
#endif

/// Internal implementation of the `EmbraceSpan` that ignores limits.
/// Only used for spans generated by the SDK internally.
class InternalEmbraceSpan: DefaultEmbraceSpan {
    @discardableResult
    override func addEvent(
        name: String,
        type: EmbraceType? = .performance,
        timestamp: Date = Date(),
        attributes: EmbraceAttributes = [:]
    ) -> EmbraceSpanEvent? {
        // isInternal=true skips the limiter so the throw is unreachable here;
        // try? collapses both that and the no-handler nil into the same return.
        return try? _addEvent(
            name: name,
            type: type,
            timestamp: timestamp,
            attributes: attributes,
            isInternal: true
        )
    }

    override func setAttribute(key: String, value: EmbraceAttributeValue?) throws {
        try _setAttribute(
            key: key,
            value: value,
            isInternal: true
        )
    }
}
