//
//  Copyright © 2025 Embrace Mobile, Inc. All rights reserved.
//

import Foundation

#if !EMBRACE_COCOAPOD_BUILDING_SDK
    import EmbraceSemantics
    import EmbraceCommonInternal
#endif

/// Internal implementation of the `EmbraceSpan` that ignores limits.
/// Only used for spans generated by the SDK internally.
class InternalEmbraceSpan: DefaultEmbraceSpan {
    override func addEvent(
        name: String,
        type: EmbraceType? = .performance,
        timestamp: Date = Date(),
        attributes: [String: String] = [:]
    ) throws {
        try _addEvent(
            name: name,
            type: type,
            timestamp: timestamp,
            attributes: attributes,
            isInternal: true
        )
    }

    override func setAttribute(key: String, value: String?) throws {
        try _setAttribute(
            key: key,
            value: value,
            isInternal: true
        )
    }
}
