//
//  Copyright © 2026 Embrace Mobile, Inc. All rights reserved.
//

import Foundation
import OpenTelemetrySdk

#if !EMBRACE_COCOAPOD_BUILDING_SDK
    import EmbraceCore
#endif

extension EmbraceIO {

    /// Class used to configure the OpenTelemetry SDK through Embrace.
    public final class OTelOptions {

        /// Used to customize OpenTelemetry resources.
        /// The resources set here will take priority over any resources generated by the Embrace SDK,
        /// except for `service.name`, `service.version` and `telemetry.sdk.language`. Those three are
        /// always set by the Embrace SDK and can't be overridden.
        public let resource: Resource?

        /// Used to add your custom `SpanProcessor`s to the pipeline.
        /// These processors will receive all the changes and attributes generated by the internal Embrace SDK span processor.
        public let spanProcessor: MultiSpanProcessor

        /// Used to add your custom `SpanExporter`s to the pipeline.
        /// These exporters will be called whenever the internal Embrace SDK span exporter exports data.
        public let spanExporter: MultiSpanExporter

        /// Used to add your custom `LogRecordProcessor`s to the pipeline.
        /// These processors will receive all the changes and attributes generated by the internal Embrace SDK log processor.
        public let logProcessor: MultiLogRecordProcessor

        /// Used to add your custom `LogRecordExporter`s to the pipeline.
        /// These exporters will be called whenever the internal Embrace SDK log exporter exports data.
        public let logExporter: MultiLogRecordExporter

        /// Determines whether the Embrace tracer and logger providers are installed as the
        /// process-wide OpenTelemetry providers.
        ///
        /// When `true`, instrumentation that resolves `OpenTelemetry.instance` — including
        /// third-party OpenTelemetry libraries that you do not configure yourself — emits through
        /// the Embrace pipeline. When `false`, the process-wide providers are left untouched and
        /// the Embrace providers are reachable only through `EmbraceIO.shared`.
        ///
        /// Defaults to `false`. These things are worth knowing before enabling it:
        ///
        /// - It only takes effect when this `start(options:)` call is the one that creates the
        ///   SDK client. The value passed to any later call is ignored.
        /// - Registration is process-global and last-writer-wins. An app that registers its own
        ///   providers after the Embrace SDK starts will displace Embrace's, and vice versa.
        /// - The Embrace SDK never removes the providers once registered, and `EmbraceIO.stop()`
        ///   does not restore the ones that were installed before.
        /// - Spans and logs arriving through these providers count against the same per-session
        ///   limits as `EmbraceIO.shared.createSpan` and `EmbraceIO.shared.log`. Chatty
        ///   instrumentation can therefore exhaust the budget your own calls draw from.
        public let registersGlobalProviders: Bool

        /// Creates a new `OTelOptions` instance to configure the OpenTelemetry SDK through Embrace.
        /// - Parameters:
        ///   - resource: Custom OpenTelemetry `Resource`. Takes priority over resources generated by the Embrace SDK,
        ///     except for `service.name`, `service.version` and `telemetry.sdk.language`, which are always set by the
        ///     Embrace SDK and can't be overridden.
        ///   - spanProcessors: Custom `SpanProcessor`s to add to the pipeline.
        ///   - spanExporters: Custom `SpanExporter`s to add to the pipeline.
        ///   - logProcessors: Custom `LogRecordProcessor`s to add to the pipeline.
        ///   - logExporters: Custom `LogRecordExporter`s to add to the pipeline.
        ///   - registersGlobalProviders: Whether to install the Embrace providers as the
        ///     process-wide OpenTelemetry providers. Defaults to `false`. See the property
        ///     documentation for the caveats that come with enabling it.
        public init(
            resource: Resource? = nil,
            spanProcessors: [SpanProcessor] = [],
            spanExporters: [SpanExporter] = [],
            logProcessors: [LogRecordProcessor] = [],
            logExporters: [LogRecordExporter] = [],
            registersGlobalProviders: Bool = false
        ) {
            self.resource = resource
            self.spanProcessor = MultiSpanProcessor(spanProcessors: spanProcessors)
            self.spanExporter = MultiSpanExporter(spanExporters: spanExporters)
            self.logProcessor = MultiLogRecordProcessor(logRecordProcessors: logProcessors)
            self.logExporter = MultiLogRecordExporter(logRecordExporters: logExporters)
            self.registersGlobalProviders = registersGlobalProviders
        }

    }
}

extension Resource {
    func toEmbraceAttributes() -> EmbraceAttributes {
        var result = EmbraceAttributes()
        for (key, value) in self.attributes {
            switch value {
            case .string(let v): result[key] = v
            case .bool(let v): result[key] = v
            case .int(let v): result[key] = v
            case .double(let v): result[key] = v
            default:
                // Arrays and other composite types are not representable
                // as EmbraceAttributeValue primitives; skip them.
                break
            }
        }
        return result
    }
}
