//
//  Copyright © 2026 Embrace Mobile, Inc. All rights reserved.
//

import Foundation
import OpenTelemetrySdk

#if !EMBRACE_COCOAPOD_BUILDING_SDK
    import EmbraceCore
#endif

extension EmbraceIO {

    /// Class used to configure the OpenTelemtry SDK through Embrace.
    public final class OTelOptions {

        // Used to customize OpenTelemetry resources.
        // The resources set here will take priority over any resources generated by the Embrace SDK.
        public let resource: Resource?

        // Used to add your custom `SpanProcessor` to the pipeline.
        // This processor will receive all the changes and attributes generated by the internal Embrace SDK span processor.
        public let spanProcessors: [SpanProcessor]

        // Used to add your custom `SpanExporter` to the pipeline.
        // This exporter will be called whenever the internal Embrace SDK span exporter exports data.
        public let spanExporter: SpanExporter?

        // Used to add your custom `LogRecordProcessor` to the pipeline.
        // This processor will receive all the changes and attributes generated by the internal Embrace SDK log processor.
        public let logProcessors: [LogRecordProcessor]

        // Used to add your custom `LogRecordExporter` to the pipeline.
        // This exporter will be called whenever the internal Embrace SDK log exporter exports data.
        public let logExporter: LogRecordExporter?

        public init(
            resource: Resource? = nil,
            spanProcessors: [SpanProcessor] = [],
            spanExporter: SpanExporter? = nil,
            logProcessors: [LogRecordProcessor] = [],
            logExporter: LogRecordExporter? = nil
        ) {
            self.resource = resource
            self.spanProcessors = spanProcessors
            self.spanExporter = spanExporter
            self.logProcessors = logProcessors
            self.logExporter = logExporter
        }

        // TODO: Clean up
        //        internal func embraceOpenTelemetryProcessors() -> [OpenTelemetryProcessor] {
        //
        //            var processors: [OpenTelemetryProcessor] = []
        //            let count = max(spanProcessors.count, logProcessors.count)
        //
        //            for i in 0..<count {
        //                var spanProcessor: SpanProcessor?
        //                if i < spanProcessors.count {
        //                    spanProcessor = spanProcessors[i]
        //                }
        //
        //                var logProcessor: LogRecordProcessor?
        //                if i < logProcessors.count {
        //                    logProcessor = logProcessors[i]
        //                }
        //
        //                processors.append(OpenTelemetryProcessor(processor: spanProcessor, logProcessor: logProcessor))
        //            }
        //
        //            return processors
        //        }
        //
        //        internal func embraceOpenTelemetryExport() -> OpenTelemetryExport {
        //            return OpenTelemetryExport(spanExporter: spanExporter, logExporter: logExporter)
        //        }
    }
}
