//
//  Copyright © 2026 Embrace Mobile, Inc. All rights reserved.
//

import Foundation
import OpenTelemetrySdk

#if !EMBRACE_COCOAPOD_BUILDING_SDK
    import EmbraceCore
#endif

extension EmbraceIO {

    /// Class used to configure the OpenTelemtry SDK through Embrace.
    public final class OTelOptions {

        // Used to customize OpenTelemetry resources.
        // The resources set here will take priority over any resources generated by the Embrace SDK.
        public let resource: Resource?

        // Used to add your custom `SpanProcessor`s to the pipeline.
        // These processors will receive all the changes and attributes generated by the internal Embrace SDK span processor.
        public let spanProcessor: MultiSpanProcessor

        // Used to add your custom `SpanExporter`s to the pipeline.
        // These exporters will be called whenever the internal Embrace SDK span exporter exports data.
        public let spanExporter: MultiSpanExporter

        // Used to add your custom `LogRecordProcessor`s to the pipeline.
        // These processors will receive all the changes and attributes generated by the internal Embrace SDK log processor.
        public let logProcessor: MultiLogRecordProcessor

        // Used to add your custom `LogRecordExporter`s to the pipeline.
        // These exporters will be called whenever the internal Embrace SDK log exporter exports data.
        public let logExporter: MultiLogRecordExporter

        public init(
            resource: Resource? = nil,
            spanProcessors: [SpanProcessor] = [],
            spanExporters: [SpanExporter] = [],
            logProcessors: [LogRecordProcessor] = [],
            logExporters: [LogRecordExporter] = []
        ) {
            self.resource = resource
            self.spanProcessor = MultiSpanProcessor(spanProcessors: spanProcessors)
            self.spanExporter = MultiSpanExporter(spanExporters: spanExporters)
            self.logProcessor = MultiLogRecordProcessor(logRecordProcessors: logProcessors)
            self.logExporter = MultiLogRecordExporter(logRecordExporters: logExporters)
        }

    }
}
