# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BrandGame' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BrandGame
  pod 'EmbraceIO', "6.15.0-rc2"
  pod 'OpenTelemetry-Swift-Sdk', '2.3.0'
  pod 'OpenTelemetry-Swift-StdoutExporter', '2.3.0'

end
