name: Build Platforms

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - id: set
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "push" && "${GITHUB_REF}" == "refs/heads/main" ]]; then
            MATRIX=$(jq -c .main .github/matrices/builds.json)
          else
            MATRIX=$(jq -c .pr .github/matrices/builds.json)
          fi
          echo "matrix=${MATRIX}" >> "$GITHUB_OUTPUT"

  build:
    needs: prepare
    name: Build ${{ matrix.platform }}, on macOS ${{ matrix.macos-version }}, with Xcode ${{ matrix.xcode_version }}
    timeout-minutes: 30
    runs-on: macos-${{ matrix.macos-version }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}

    steps:
    - name: Select Xcode
      # See https://github.com/actions/runner-images/blob/main/images/macos/macos-15-Readme.md
      run: |
        sudo xcode-select -s /Applications/Xcode_${MATRIX_XCODE_VERSION}.app
        xcodebuild -version
      env:
        MATRIX_XCODE_VERSION: ${{ matrix.xcode_version }}

    - name: Ensure the Platform is Downloaded
      if: ${{ matrix.platform != 'macOS' && matrix.platform != 'mac-catalyst' }}
      run: |
        xcodebuild -runFirstLaunch
        xcrun simctl list
        xcodebuild -downloadPlatform ${MATRIX_PLATFORM}
        xcodebuild -runFirstLaunch
      env:
        MATRIX_PLATFORM: ${{ matrix.platform }}

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      timeout-minutes: 4
      with:
        persist-credentials: false

    - name: Cache SwiftPM packages
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: ~/Library/Developer/Xcode/DerivedData/embrace-apple-sdk-*/SourcePackages
        key: swiftpm-${{ runner.os }}-${{ hashFiles('Package.resolved') }}
        restore-keys: swiftpm-${{ runner.os }}-

    - name: Build
      uses: ./.github/actions/run-xcodebuild
      with:
        workspace: ".swiftpm/xcode/package.xcworkspace"
        scheme: EmbraceIO-Package
        platform: ${{ matrix.platform }}
        platform-version: ${{ matrix.platform-version }}
        arch: arm64
        action: build
