name: Build Example Apps

on:
  workflow_call: {}
  workflow_dispatch: {}
  pull_request: {}

permissions:
  contents: read

jobs:
  build-brandgame-app:
    name: Build BrandGame App
    timeout-minutes: 20
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        xcode_version: ["15.4"]
    steps:
      - name: Select Xcode
        # See https://github.com/actions/runner-images/blob/main/images/macos/macos-15-Readme.md
        run: |
          sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode_version }}.app
          xcodebuild -version

      - uses: actions/checkout@v4
        timeout-minutes: 4
        with:
          persist-credentials: false

      - name: xcodebuild
        env:
          PROJECT_DIR: ./Examples/BrandGame
          PROJECT_NAME: BrandGame.xcodeproj
          SCHEME: BrandGame
          IS_XCTEST: true # Needed to disable SwiftLint -> SwiftSyntax plugin dependency build issue
        run: |
          set -o pipefail

          BUILD_DIR="$PROJECT_DIR/.build"

          xcodebuild build -project "$PROJECT_DIR/$PROJECT_NAME" \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO \
            -scheme $SCHEME \
            -sdk iphonesimulator \
            -derivedDataPath $BUILD_DIR/DerivedData \
            -clonedSourcePackagesDirPath $BUILD_DIR \
          | xcpretty

  build-demoobjc-app:
    name: Build Objc Demo App
    timeout-minutes: 20
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        xcode_version: ["15.4"]
    steps:
      - name: Select Xcode
        # See https://github.com/actions/runner-images/blob/main/images/macos/macos-15-Readme.md
        run: |
          sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode_version }}.app
          xcodebuild -version

      - uses: actions/checkout@v4
        timeout-minutes: 4
        with:
          persist-credentials: false

      - name: xcodebuild
        env:
          PROJECT_DIR: ./Examples/DemoObjectiveC
          PROJECT_NAME: DemoObjectiveC.xcodeproj
          SCHEME: DemoObjectiveC
          IS_XCTEST: true # Needed to disable SwiftLint -> SwiftSyntax plugin dependency build issue
        run: |
          set -o pipefail

          BUILD_DIR="$PROJECT_DIR/.build"

          xcodebuild build -project "$PROJECT_DIR/$PROJECT_NAME" \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO \
            -scheme $SCHEME \
            -sdk iphonesimulator \
            -derivedDataPath $BUILD_DIR/DerivedData \
            -clonedSourcePackagesDirPath $BUILD_DIR \
          | xcpretty
