name: Perf Check

on:
  pull_request:
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  ITERATIONS: 20
  SHOULD_CLEAN: 1
  THRESHOLD_PCT: 5.0
  TESTS: |
    EmbraceIOTests/PerformanceTests
  BENCHMARKS: |
    BenchmarksUITests

jobs:
  perf:
    runs-on: macos-latest
    
    steps:

      # checkout this PR branch
      - name: Checkout PR
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install scipy pygithub

      - name: Copy binaries
        run: |
          mkdir -p $HOME/embrace/bin
          cp bin/platform $HOME/embrace/bin/platform
          cp bin/perf $HOME/embrace/bin/perf
          cp bin/benchmarks $HOME/embrace/bin/benchmarks
          cp bin/perfcomp.py $HOME/embrace/bin/perfcomp.py
          cp bin/destinations $HOME/embrace/bin/destinations
          cp bin/run_regression_tests $HOME/embrace/bin/run_regression_tests
          chmod +x $HOME/embrace/bin/perf
          chmod +x $HOME/embrace/bin/benchmarks
          chmod +x $HOME/embrace/bin/perfcomp.py
          chmod +x $HOME/embrace/bin/destinations
          chmod +x $HOME/embrace/bin/run_regression_tests

      - name: Run PR perf tests
        id: perfpr
        run: |
          /$HOME/embrace/bin/run_regression_tests

        # checkout the main branch
      - name: Checkout Main
        uses: actions/checkout@v4
        with:
          ref: main
          persist-credentials: false
      
      - name: Run Main perf tests
        id: perfmain
        run: |
          $HOME/embrace/bin/run_regression_tests

      - name: Run Performance Comparison
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERF_PR: ${{ steps.perfpr.outputs.out }}
          PERF_MAIN: ${{ steps.perfmain.outputs.out }}
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          python $HOME/embrace/bin/perfcomp.py
