name: Test Upload SDK Version Action

on:
  push:
    branches:
      - test-ci-release-checks
  workflow_dispatch:
    inputs:
      platform:
        description: "Target platform (ios, android, flutter, reactnative, unity)"
        required: true
        default: ios
      version:
        description: "SDK version to publish"
        required: true
        default: 1.2.3
      dryRun:
        description: "Dry run (true/false)"
        required: false
        default: "true"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test action from commit
        uses: embrace-io/public-actions/upload-sdk-version@95f23d7c17df9ad4e02aa81bd154462cdc869807
        with:
          platform: 'ios'
          version: '1.2.3'
          dryRun: 'true'
          sdkVersionUrl: ${{ vars.SDK_VERSION_URL }}
        env:
          SDK_VERSION_TOKEN: ${{ secrets.SDK_VERSION_TOKEN }}
